apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
  - name: flask-container
    image: 995040/kubernetes:example
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
