apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - image: 995040/kubernetes:example
          imagePullPolicy: Always
          name: flask
          ports:
            - containerPort: 8080
