apiVersion: v1
kind: Service
metadata:
  name: flask-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080  	# specifies the port on which the service gets requests
    protocol: TCP
    targetPort: 8080  	# The port at which incoming requests are forwarded
  selector:  		# property required to select pods with these selectors
    app: flask
