apiVersion: v1
kind: Service
metadata:  
  name: flask-nodeport-service
spec:
  selector:    
    app: flask
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31780
    protocol: TCP
