apiVersion: v1
kind: Service
metadata:  
  name: flask-nodeport-service
spec:
  selector:    
    app: flask
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31780
    protocol: TCP
